language: python
python:
  - "3.8.1"

services:
  - postgresql

env:
  -DJANGO=3.0.3 DB=postgresql

install:
  - "pip install -r requirements/requirements.txt" 
  - "pip install -r requirements/development.txt"

before_script: 
  - postgresql -e 'create database test;' -u root

script:
  - coverage run --source='.' manage.py test apps