branches:
  only:
    - master

branches:
  except:
    - development
    - initial
    - consolidation

language: python
python:
  - "3.8.1"

services:
  - postgresql

env:
  - DJANGO=3.0.3 DB=postgresql

before_install:
  - export DJANGO_SETTINGS_MODULE=djangoopenbadges.settings.development

install:
  - "pip install -r requirements/requirements.txt" 
  - "pip install -r requirements/development.txt"

before_script: 
  - psql -c "CREATE DATABASE travisdb;" -U postgres

script:
  - python manage.py makemigrations core
  - python manage.py makemigrations diplomas

  - python manage.py migrate core
  - python manage.py migrate auth
  - python manage.py migrate contenttypes
  - python manage.py migrate admin
  - python manage.py migrate sessions
  - python manage.py migrate diplomas

  - coverage run --source='.' manage.py test apps

after_success:
- coveralls