language: python
python:
  - "3.8.1"

services:
  - postgresql

env:
  - DJANGO=3.0.3 DB=mysql

before_install:
  - export DJANGO_SETTINGS_MODULE=djangoopendiplomas.config.development

install:
  - "pip install -r requirements/requirements.txt" 
  - "pip install -r requirements/development.txt"

before_script: 
  - psql -c "CREATE DATABASE test;" -U postgres

script:
  - coverage run --source='.' manage.py test apps