language: python
python:
  - "3.8.1"

services:
  - docker

install:
  - "pip install -r requirements/requirements.txt" 
  - "pip install -r requirements/development.txt"

before_script: pip install docker-compose

script:
  - docker-compose up --build
  - docker run -e POSTGRES_USER=project -e POSTGRES_PASSWORD=project -e POSTGRES_DB=dop library/postgres
  - docker-compose run --rm web sh -c "coverage run --source='.' manage.py test apps"